### ISSUE TITLE
Add small subtitle below title

### ISSUE THREAD

**Issue by kodehat** [kodehat/portkey#12]
Could be empty by default (and hidden) and shown when filled.

**Comment by gargantuadev** [comment]
Hello there! 
I would like to do it, may you kindly add the hacktoberfest label to the issue and assign it to me? Thankssssss

**Comment by kodehat** [comment]
Hi,
I have already added the `hacktoberfest` topic to the repository itself, which should be enough to make its issues count for Hacktoberfest. 😉

**Comment by gargantuadev** [comment]
Hello again, I tried to install it, but it's giving me issues. Has this been deployed for a Linux Machine?

**Comment by kodehat** [comment]
Yes. Works on Linux/macOS and Windows. Make sure you have followed the hints/instructions in the README.

**Comment by gargantuadev** [comment]
I don't know ahah, I installed as it is written, but then honestly I don't know how to start it....
I used air, but it giving some errors, for the frontend I was running the npm run watch (I already did the build), but on my side is not working, do you have any suggestion?

**Comment by kodehat** [comment]
Make sure that you have also generated the HTML user interfaces using `templ`. Otherwise posting some details regarding the errors you receive, could also help to understand your problems.

**Comment by gargantuadev** [comment]
Hello there, I receive this error when I do "air" from the terminal to run the backend (I installed air as suggested in the README):

![image](https://github.com/user-attachments/assets/f7194c58-03ad-4685-bafb-b1d6fcec2f88)

The other problem is (Imho) that build.sh file runs only in Linux and not in Windows. I tried to convert it to a build.bat and tried to change the variable cmd in .air.toml file but does not work either.

When I run air, in the command line I'm seeing this:

```
  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.61.0, built with Go go1.23.2

watching .
!exclude assets
watching docs
watching docs\images
watching internal
watching internal\build
watching internal\components
watching internal\config
watching internal\metrics
watching internal\models
watching internal\server
watching internal\utils
!exclude node_modules
!exclude static
!exclude tmp
building...
CMD will not recognize non .exe file for execution, path: npm run build && templ generate . && build.bat

> portkey@0.0.0 build
> npm run build:css && npm run build:js


> portkey@0.0.0 build:css
> tailwindcss -i assets/css/main.css build -m -o static/css/main.css


Rebuilding...

Done in 238ms.

> portkey@0.0.0 build:js
> esbuild assets/js/main.js --bundle --minify --sourcemap --outfile=static/js/main.js


  static\js\main.js      102.4kb
  static\js\main.js.map  420.3kb

Done in 19ms
(✓) Complete [ updates=5 duration=57.865ms ]
[Go vgo] Building portkey in .\ at  with commit N/A in version dev.
malformed import path "github.com/kodehat/portkey/internal/build.BuildTime=": invalid char '='
malformed import path "-X": leading dash
malformed import path "github.com/kodehat/portkey/internal/build.CommitHash=N/A": invalid char '='
malformed import path "github.com/kodehat/portkey/internal/build.Version=dev": invalid char '='
malformed import path "github.com/kodehat/portkey/internal/build.GoVersion=go": invalid char '='
running...
The system cannot find the file LOGLEVEL=DEBUG.
Process Exit with Code: 1
```

The cmd that I changed is this:
`cmd = "npm run build && templ generate . && build.bat"`

And the .bat file is this one:
```
@echo off
setlocal

REM Define variables
set TARGET_PACKAGE=github.com/kodehat/portkey/internal/build
for /f "tokens=2 delims==" %%i in ('powershell -command "Get-Date -Format yyyy.MM.dd_HH:mm:ss -AsUTC"') do set BUILD_TIME=%%i
set commit_hash=
set version=dev
set go_version=unknown
set output=.\

REM Parse arguments
:parse_args
if "%1"=="" goto args_done
if "%1"=="-o" (
    set output=%2
    shift
) else if "%1"=="-v" (
    set version=%2
    shift
)
shift
goto parse_args
:args_done

REM Get the latest commit hash
for /f %%i in ('git log -1 --pretty=format:%%h 2^>nul') do set commit_hash=%%i
if "%commit_hash%"=="" (
    set commit_hash=N/A
)

REM Get Go version
for /f %%i in ('go version 2^>nul') do (
    for %%j in (%%i) do (
        set go_version=%%j
    )
)

REM Set the ldflags for the build
set FLAG=-X %TARGET_PACKAGE%.BuildTime=%BUILD_TIME%
set FLAG=%FLAG% -X %TARGET_PACKAGE%.CommitHash=%commit_hash%
set FLAG=%FLAG% -X %TARGET_PACKAGE%.Version=%version%
set FLAG=%FLAG% -X %TARGET_PACKAGE%.GoVersion=%go_version%

REM Build the Go binary
echo [Go v%go_version%] Building portkey in %output% at %BUILD_TIME% with commit %commit_hash% in version %version%.
set CGO_ENABLED=0
go build -o "%output%" -ldflags "%FLAG%"

endlocal

```

**Comment by kodehat** [comment]
Ah, good point. I already thought about issues like this, but as I‘m developing on Linux, I never experienced problems. Just remove `LOGLEVEL=DEBUG` from the `full_bin` line in `.air.toml`. As it‘s just for debug output,  it’s not that important.
I will sort this out for Windows in a dedicated issue later.

**Comment by gargantuadev** [comment]
No worries, I'm trying to buy a new pc so I can install Linux on it, but on this one I really can't ahah.
I'm still receiving an error:
  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.61.0, built with Go go1.23.2

watching .
!exclude assets
watching docs
watching docs\images
watching internal
watching internal\build
watching internal\components
watching internal\config
watching internal\metrics
watching internal\models
watching internal\server
watching internal\utils
!exclude node_modules
!exclude static
!exclude tmp
building...
CMD will not recognize non .exe file for execution, path: npm run build && templ generate . && build.bat

> portkey@0.0.0 build
> npm run build:css && npm run build:js


> portkey@0.0.0 build:css
> tailwindcss -i assets/css/main.css build -m -o static/css/main.css


Rebuilding...

Done in 313ms.

> portkey@0.0.0 build:js
> esbuild assets/js/main.js --bundle --minify --sourcemap --outfile=static/js/main.js


  static\js\main.js      102.4kb
  static\js\main.js.map  420.3kb

Done in 25ms
(✓) Complete [ updates=5 duration=93.9812ms ]
[Go vgo] Building portkey in .\ at  with commit N/A in version dev.
malformed import path "github.com/kodehat/portkey/internal/build.BuildTime=": invalid char '='
malformed import path "-X": leading dash
malformed import path "github.com/kodehat/portkey/internal/build.CommitHash=N/A": invalid char '='
malformed import path "github.com/kodehat/portkey/internal/build.Version=dev": invalid char '='
malformed import path "github.com/kodehat/portkey/internal/build.GoVersion=go": invalid char '='
running...
CMD will not recognize non .exe file for execution, path: "path_to_portkey\portkey"
'"path_to_portkey\portkey"' is not recognized as an internal or external command,
operable program or batch file.
Process Exit with Code: 1


Still a problem because the .bat probably is not correct somehow :/

**Comment by kodehat** [comment]
I have just changed some stuff in `.air.toml` by removing usage of `build.sh` and DEBUG log level, so that local development with `air` should work across different operating systems.
